[package]
name = "taskbar"
version = "0.1.0"
edition = "2024"

[dependencies]
stil_core = { path = "../stil_core" }
gtk4 = { version = "0.10.3", features = ["v4_20"] }
gtk4-layer-shell = { version = "0.7.1", features = ["v1_3"] }
