[package]
name = "daemon"
version = "0.1.0"
edition = "2024"

[dependencies]
proto_rust = { path="../proto_rust" }
tracing = "0.1.41"
tracing-subscriber = "0.3.20"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
protobuf = "4.33.0-release"
rayon = "1.11.0"
